# code: language=ansible
---
- name: Verify
  hosts: all
  gather_facts: true
  tasks:
    - name: Print env
      ansible.builtin.debug:
        msg:
          - "ansible_version => {{ ansible_facts['version'] }}"
          - "ansible_distribution => {{ ansible_facts['distribution'] }}"
          - "ansible_distribution_major_version => {{ ansible_facts['distribution_major_version'] }}"
          - "ansible_os_family  => {{ ansible_facts['os_family'] }}"
          - "ansible_system  => {{ ansible_facts['system'] }}"
