name: publish

on:
  release:
    types: [published]

jobs:
  publish:
    uses: wittdennis/pipelines/.github/workflows/ansible-galaxy-publish.yaml@29f41b6d8146f7189dce232aa5a23ee635f7cbe0 # 2.0.2
    secrets:
      galaxy-api-token: ${{ secrets.ANSIBLE_GALAXY_API_KEY }}
