name: publish

on:
  release:
    types: [published]

jobs:
  publish:
    uses: wittdennis/pipelines/.github/workflows/ansible-galaxy-publish.yaml@767c74fb5809ef0cd9fc398630d5d21d81532faa # 2.0.37
    secrets:
      galaxy-api-token: ${{ secrets.ANSIBLE_GALAXY_API_KEY }}
