name: create-release

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        default: "auto"
        required: false
        description: "Used to manually set the version"

jobs:
  release:
    uses: wittdennis/pipelines/.github/workflows/cog-release.yaml@d7142ea4fc5237aae7ec616148530adc3577ec7d # 2.0.23
    with:
      version: ${{ inputs.version }}
    secrets:
      release-token: ${{ secrets.RELEASE_TOKEN}}
